// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: internal/proto/api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchingEngine_PlaceLimitOrder_FullMethodName  = "/pb.matchingEngine/PlaceLimitOrder"
	MatchingEngine_PalceMarketOrder_FullMethodName = "/pb.matchingEngine/PalceMarketOrder"
	MatchingEngine_CancelOrder_FullMethodName      = "/pb.matchingEngine/CancelOrder"
	MatchingEngine_GetCurrentOrders_FullMethodName = "/pb.matchingEngine/GetCurrentOrders"
	MatchingEngine_GetOrderHistory_FullMethodName  = "/pb.matchingEngine/GetOrderHistory"
	MatchingEngine_AddOrderBook_FullMethodName     = "/pb.matchingEngine/AddOrderBook"
	MatchingEngine_DeleteOrderBook_FullMethodName  = "/pb.matchingEngine/DeleteOrderBook"
)

// MatchingEngineClient is the client API for MatchingEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchingEngineClient interface {
	PlaceLimitOrder(ctx context.Context, in *PlaceOrderReq, opts ...grpc.CallOption) (*PlaceOrderRes, error)
	PalceMarketOrder(ctx context.Context, in *PlaceOrderReq, opts ...grpc.CallOption) (*PlaceOrderRes, error)
	CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderRes, error)
	GetCurrentOrders(ctx context.Context, in *GetCurrentOrdersReq, opts ...grpc.CallOption) (*GetCurrentOrdersRes, error)
	GetOrderHistory(ctx context.Context, in *GetOrderHistoryReq, opts ...grpc.CallOption) (*GetOrderHistoryRes, error)
	AddOrderBook(ctx context.Context, in *AddOrderBookReq, opts ...grpc.CallOption) (*AddOrderBookRes, error)
	DeleteOrderBook(ctx context.Context, in *DeleteOrderBookReq, opts ...grpc.CallOption) (*DeleteOrderBookRes, error)
}

type matchingEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchingEngineClient(cc grpc.ClientConnInterface) MatchingEngineClient {
	return &matchingEngineClient{cc}
}

func (c *matchingEngineClient) PlaceLimitOrder(ctx context.Context, in *PlaceOrderReq, opts ...grpc.CallOption) (*PlaceOrderRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceOrderRes)
	err := c.cc.Invoke(ctx, MatchingEngine_PlaceLimitOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingEngineClient) PalceMarketOrder(ctx context.Context, in *PlaceOrderReq, opts ...grpc.CallOption) (*PlaceOrderRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceOrderRes)
	err := c.cc.Invoke(ctx, MatchingEngine_PalceMarketOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingEngineClient) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderRes)
	err := c.cc.Invoke(ctx, MatchingEngine_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingEngineClient) GetCurrentOrders(ctx context.Context, in *GetCurrentOrdersReq, opts ...grpc.CallOption) (*GetCurrentOrdersRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentOrdersRes)
	err := c.cc.Invoke(ctx, MatchingEngine_GetCurrentOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingEngineClient) GetOrderHistory(ctx context.Context, in *GetOrderHistoryReq, opts ...grpc.CallOption) (*GetOrderHistoryRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderHistoryRes)
	err := c.cc.Invoke(ctx, MatchingEngine_GetOrderHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingEngineClient) AddOrderBook(ctx context.Context, in *AddOrderBookReq, opts ...grpc.CallOption) (*AddOrderBookRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddOrderBookRes)
	err := c.cc.Invoke(ctx, MatchingEngine_AddOrderBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingEngineClient) DeleteOrderBook(ctx context.Context, in *DeleteOrderBookReq, opts ...grpc.CallOption) (*DeleteOrderBookRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteOrderBookRes)
	err := c.cc.Invoke(ctx, MatchingEngine_DeleteOrderBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchingEngineServer is the server API for MatchingEngine service.
// All implementations must embed UnimplementedMatchingEngineServer
// for forward compatibility.
type MatchingEngineServer interface {
	PlaceLimitOrder(context.Context, *PlaceOrderReq) (*PlaceOrderRes, error)
	PalceMarketOrder(context.Context, *PlaceOrderReq) (*PlaceOrderRes, error)
	CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderRes, error)
	GetCurrentOrders(context.Context, *GetCurrentOrdersReq) (*GetCurrentOrdersRes, error)
	GetOrderHistory(context.Context, *GetOrderHistoryReq) (*GetOrderHistoryRes, error)
	AddOrderBook(context.Context, *AddOrderBookReq) (*AddOrderBookRes, error)
	DeleteOrderBook(context.Context, *DeleteOrderBookReq) (*DeleteOrderBookRes, error)
	mustEmbedUnimplementedMatchingEngineServer()
}

// UnimplementedMatchingEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchingEngineServer struct{}

func (UnimplementedMatchingEngineServer) PlaceLimitOrder(context.Context, *PlaceOrderReq) (*PlaceOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceLimitOrder not implemented")
}
func (UnimplementedMatchingEngineServer) PalceMarketOrder(context.Context, *PlaceOrderReq) (*PlaceOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PalceMarketOrder not implemented")
}
func (UnimplementedMatchingEngineServer) CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedMatchingEngineServer) GetCurrentOrders(context.Context, *GetCurrentOrdersReq) (*GetCurrentOrdersRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentOrders not implemented")
}
func (UnimplementedMatchingEngineServer) GetOrderHistory(context.Context, *GetOrderHistoryReq) (*GetOrderHistoryRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderHistory not implemented")
}
func (UnimplementedMatchingEngineServer) AddOrderBook(context.Context, *AddOrderBookReq) (*AddOrderBookRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrderBook not implemented")
}
func (UnimplementedMatchingEngineServer) DeleteOrderBook(context.Context, *DeleteOrderBookReq) (*DeleteOrderBookRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOrderBook not implemented")
}
func (UnimplementedMatchingEngineServer) mustEmbedUnimplementedMatchingEngineServer() {}
func (UnimplementedMatchingEngineServer) testEmbeddedByValue()                        {}

// UnsafeMatchingEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchingEngineServer will
// result in compilation errors.
type UnsafeMatchingEngineServer interface {
	mustEmbedUnimplementedMatchingEngineServer()
}

func RegisterMatchingEngineServer(s grpc.ServiceRegistrar, srv MatchingEngineServer) {
	// If the following call pancis, it indicates UnimplementedMatchingEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchingEngine_ServiceDesc, srv)
}

func _MatchingEngine_PlaceLimitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServer).PlaceLimitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngine_PlaceLimitOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServer).PlaceLimitOrder(ctx, req.(*PlaceOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingEngine_PalceMarketOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServer).PalceMarketOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngine_PalceMarketOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServer).PalceMarketOrder(ctx, req.(*PlaceOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingEngine_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngine_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServer).CancelOrder(ctx, req.(*CancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingEngine_GetCurrentOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServer).GetCurrentOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngine_GetCurrentOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServer).GetCurrentOrders(ctx, req.(*GetCurrentOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingEngine_GetOrderHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServer).GetOrderHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngine_GetOrderHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServer).GetOrderHistory(ctx, req.(*GetOrderHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingEngine_AddOrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrderBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServer).AddOrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngine_AddOrderBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServer).AddOrderBook(ctx, req.(*AddOrderBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingEngine_DeleteOrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrderBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServer).DeleteOrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngine_DeleteOrderBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServer).DeleteOrderBook(ctx, req.(*DeleteOrderBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchingEngine_ServiceDesc is the grpc.ServiceDesc for MatchingEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchingEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.matchingEngine",
	HandlerType: (*MatchingEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceLimitOrder",
			Handler:    _MatchingEngine_PlaceLimitOrder_Handler,
		},
		{
			MethodName: "PalceMarketOrder",
			Handler:    _MatchingEngine_PalceMarketOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _MatchingEngine_CancelOrder_Handler,
		},
		{
			MethodName: "GetCurrentOrders",
			Handler:    _MatchingEngine_GetCurrentOrders_Handler,
		},
		{
			MethodName: "GetOrderHistory",
			Handler:    _MatchingEngine_GetOrderHistory_Handler,
		},
		{
			MethodName: "AddOrderBook",
			Handler:    _MatchingEngine_AddOrderBook_Handler,
		},
		{
			MethodName: "DeleteOrderBook",
			Handler:    _MatchingEngine_DeleteOrderBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/api.proto",
}
